export const metadata = {
  title: "Timeline",
  description: "Generated by create next app",
};

export default function TimeLineLayout({ children }) {
  return (
    <div
      className={`antialiased font-poppins w-full h-full bg-[#15171c] overflow-x-hidden flex justify-center flex-col items-center`}
    >
      {children}
    </div>
  );
}
