export const metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function ProfileLayout({ children }) {
  return (
    <div
      className={`antialiased font-poppins w-full h-full bg-black overflow-x-hidden flex justify-center flex-col items-center`}
    >
      {children}
    </div>
  );
}
